example_callbacks:
  default_args:
    start_date: "2024-01-01"
    on_failure_callback:
      callback: airflow.providers.slack.notifications.slack.send_slack_notification
      slack_conn_id: slack_conn_id
      text: |
        :red_circle: Task Failed.
        This task has failed and needs to be addressed.
        Please remediate this issue ASAP.
      channel: "#channel"
  schedule_interval: "@daily"
  catchup: False
  on_failure_callback:
    callback: customized.callbacks.custom_callbacks.output_message
    param1: param1
    param2: param2
  task_groups:
    task_group_1:
      default_args:
        on_success_callback: $CONFIG_ROOT_DIR.print_hello.print_hello_from_callback
      dependencies: [start]
  tasks:
    start:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: "echo 1"
    task_1:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: "echo 1"
    task_2:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: "echo 1"
      on_failure_callback_name: print_hello_from_callback
      on_failure_callback_file: $CONFIG_ROOT_DIR/print_hello.py
    end:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: "echo 1"
      dependencies:
        - task_group_1
